extract func "echo" and "run"

diff --git a/Zsh/zshrc b/Zsh/zshrc
--- a/Zsh/zshrc
+++ b/Zsh/zshrc
@@ -102,13 +102,43 @@ export PATH="$(python3 -m site --user-base)/bin:$PATH"  # Python User Site-Packa
 
 source $ZSH/oh-my-zsh.sh
 
+_echo() {
+    local UNDERLINE=$'\e[4m'
+    local DIM=$'\e[2m'
+    local RESET=$'\e[0m'
 
-run_command() {
-    underline=$'\e[4m'
-    dim=$'\e[2m'
-    reset=$'\e[0m'
-    echo "\n${dim}\$${reset} ${underline}$1${reset}"
-    eval $1
+    local type="$1"
+    shift
+    local message="$@"
+
+    case "$type" in
+        --err)
+            echo -e "${DIM}[${RESET}${UNDERLINE}Error${RESET}${DIM}]${RESET} $message" >&2
+            ;;
+        --warn)
+            echo -e "${DIM}[${RESET}Warning${DIM}]${RESET} $message"
+            ;;
+        --info)
+            echo -e "${DIM}[Info]${RESET} $message"
+            ;;
+        --title)
+            echo ""
+            echo -e "${DIM}============${RESET}"
+            echo -e "${DIM}|${RESET} $message"
+            echo -e "${DIM}============${RESET}"
+            ;;
+        --command)
+            echo -e "${DIM}\$${RESET} ${UNDERLINE}$message${RESET}"
+            ;;
+        *)
+            echo "$type $message"
+            ;;
+    esac
+}
+
+_verbose_run() {
+    _echo --command "$1"
+    eval "$1"
 }
 
 fzfcd() {  # use fzf to select a file, and cd to its directory
@@ -116,34 +146,64 @@ fzfcd() {  # use fzf to select a file, and cd to its directory
 }
 
 up() {  # upgrade all packages
-    case $(uname -s) in
-        Darwin)  # macOS
-            run_command "python3 -m pip install --upgrade pip"
-            run_command 'brew update'
-            run_command 'brew upgrade'
-            run_command 'brew list --cask | xargs brew upgrade --cask'
-            run_command 'brew cleanup'
-            ;;
-        Linux)  # Linux
-            run_command 'sudo apt update'
-            run_command 'sudo apt dist-upgrade -y'
-            run_command 'sudo apt auto-remove -y'
-            run_command 'sudo snap refresh'
-            ;;
-    esac
-    run_command "pipx upgrade-all"  # 20s
+    upgrade_pipx() {
+        _echo --title 'Upgrade Pipx Packages'
+        _verbose_run "pipx upgrade-all"  # 20s
+    }
+    upgrade_pip() {
+        _echo --title 'Upgrade pip'
+        _verbose_run "python3 -m pip install --upgrade pip"
+    }
+    upgrade_brew() {
+        if [[ "$(uname -s)" == "Darwin" ]]; then  # only work on macOS
+            _echo --title 'Upgrade Brew Packages'
+            _verbose_run 'brew update'
+            _verbose_run 'brew upgrade'
+            _verbose_run 'brew list --cask | xargs brew upgrade --cask'
+            _verbose_run 'brew cleanup'
+        fi
+    }
+    upgrade_apt() {
+        if [[ "$(uname -s)" == "Linux" ]]; then  # only work on Linux
+            _echo --title 'Upgrade Apt Packages'
+            _verbose_run 'sudo apt update'
+            _verbose_run 'sudo apt dist-upgrade -y'
+            _verbose_run 'sudo apt auto-remove -y'
+        fi
+    }
+    upgrade_snap() {
+        if [[ "$(uname -s)" == "Linux" ]]; then  # only work on Linux
+            _echo --title 'Upgrade Snap Packages'
+            _verbose_run 'sudo snap refresh'
+        fi
+    }
+    local available_pms=('pip' 'pipx' 'brew' 'apt' 'snap')  # Available package managers
+    if [[ $# -eq 0 ]]; then  # Run 'up' to run all upgrades.
+        for pm in "${available_pms[@]}"; do
+            eval "upgrade_$pm"
+        done
+    else  # Run 'up pip brew' for brew and pip upgrades only.
+        for arg in "$@"; do
+            if [[ " ${available_pms[*]} " =~ " $arg " ]]; then  # $arg is in available_pms
+                eval "upgrade_$arg"
+            else
+                echo "[Error] Unknown package manager: $arg"
+                echo "[Info] Supported package managers: ${available_pms[*]}"
+            fi
+        done
+    fi
 }
 
 venv() {  # deactivate if in a venv, or activate .venv/bin/activate
     if [[ -n "$VIRTUAL_ENV" ]]; then
-        run_command "deactivate"
+        _verbose_run "deactivate"
     elif [[ -d "./.venv" ]]; then
-        run_command "source ./.venv/bin/activate"
+        _verbose_run "source ./.venv/bin/activate"
     else
-        run_command "uv venv"
+        _verbose_run "uv venv"
         for file in "requirements.txt" "requirements-dev.txt" "requirements-opt.txt"; do
             if [[ -f "./$file" ]]; then
-                run_command "uv pip install -r ./$file"
+                _verbose_run "uv pip install -r ./$file"
             fi
         done
         venv  # activate the venv
