Update zshrc

diff --git a/Zsh/zshrc b/Zsh/zshrc
--- a/Zsh/zshrc
+++ b/Zsh/zshrc
@@ -1,5 +1,77 @@
-# If you come from bash you might have to change your $PATH.
-# export PATH=$HOME/bin:/usr/local/bin:$PATH
+# Utility functions for zshrc
+_echo() {  # Print message with different types
+    local UNDERLINE=$'\e[4m'
+    local DIM=$'\e[2m'
+    local RESET=$'\e[0m'
+
+    local type="$1"
+    shift
+    local message="$@"
+
+    case "$type" in
+        --err)
+            echo -e "${DIM}[${RESET}${UNDERLINE}Error${RESET}${DIM}]${RESET} $message" >&2
+            ;;
+        --warn)
+            echo -e "${DIM}[${RESET}Warning${DIM}]${RESET} $message"
+            ;;
+        --info)
+            echo -e "${DIM}[Info]${RESET} $message"
+            ;;
+        --debug)
+            echo -e "[Debug] $message"
+            ;;
+        --title)
+            echo ""
+            if [[ $(echo "═║╔╗╚╝") == "═║╔╗╚╝" ]]; then
+                local horizontal_bar=$(printf '═%.0s' $(seq 1 ${#message}))
+                local vertical_bar="║"
+                local top_left="╔═"
+                local top_right="═╗"
+                local bottom_left="╚═"
+                local bottom_right="═╝"
+            else
+                local horizontal_bar=$(printf '=%.0s' $(seq 1 ${#message}))
+                local vertical_bar="|"
+                local top_left="+="
+                local top_right="=+"
+                local bottom_left="+="
+                local bottom_right="=+"
+            fi
+            echo -e "${DIM}${top_left}${horizontal_bar}${top_right}${RESET}"
+            echo -e "${DIM}${vertical_bar}${RESET} $message ${DIM}${vertical_bar}${RESET}"
+            echo -e "${DIM}${bottom_left}${horizontal_bar}${bottom_right}${RESET}"
+            ;;
+        --command)
+            echo -e "${DIM}\$${RESET} ${UNDERLINE}$message${RESET}"
+            ;;
+        *)
+            echo "$type $message"
+            ;;
+    esac
+}
+
+_verbose_run() {  # Print command before running it
+    _echo --command "$1"
+    eval "$1"
+}
+
+_has_cmd() {  # Check if command exists
+    # Usage:
+    #    _has_cmd 'cmd'  # Check if cmd exists
+    #    _has_cmd -v/--verbose 'cmd'  # Check if cmd exists, and print error message if not exists
+    local verbose=0
+    if [[ "$1" == '-v' || "$1" == '--verbose' ]]; then
+        verbose=1
+        shift
+    fi
+    if command -v "$@" > /dev/null 2>&1; then  # Command exists
+        return 0
+    else  # Command not exists
+        [[ "$verbose" == 1 ]] && _echo --err "Command not found: $1"
+        return 1
+    fi
+}
 
 # Path to your oh-my-zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
@@ -107,80 +179,6 @@ if _has_cmd zoxide; then
 fi
 
 source $ZSH/oh-my-zsh.sh
-
-_echo() {  # Print message with different types
-    local UNDERLINE=$'\e[4m'
-    local DIM=$'\e[2m'
-    local RESET=$'\e[0m'
-
-    local type="$1"
-    shift
-    local message="$@"
-
-    case "$type" in
-        --err)
-            echo -e "${DIM}[${RESET}${UNDERLINE}Error${RESET}${DIM}]${RESET} $message" >&2
-            ;;
-        --warn)
-            echo -e "${DIM}[${RESET}Warning${DIM}]${RESET} $message"
-            ;;
-        --info)
-            echo -e "${DIM}[Info]${RESET} $message"
-            ;;
-        --debug)
-            echo -e "[Debug] $message"
-            ;;
-        --title)
-            echo ""
-            if [[ $(echo "═║╔╗╚╝") == "═║╔╗╚╝" ]]; then
-                local horizontal_bar=$(printf '═%.0s' $(seq 1 ${#message}))
-                local vertical_bar="║"
-                local top_left="╔═"
-                local top_right="═╗"
-                local bottom_left="╚═"
-                local bottom_right="═╝"
-            else
-                local horizontal_bar=$(printf '=%.0s' $(seq 1 ${#message}))
-                local vertical_bar="|"
-                local top_left="+="
-                local top_right="=+"
-                local bottom_left="+="
-                local bottom_right="=+"
-            fi
-            echo -e "${DIM}${top_left}${horizontal_bar}${top_right}${RESET}"
-            echo -e "${DIM}${vertical_bar}${RESET} $message ${DIM}${vertical_bar}${RESET}"
-            echo -e "${DIM}${bottom_left}${horizontal_bar}${bottom_right}${RESET}"
-            ;;
-        --command)
-            echo -e "${DIM}\$${RESET} ${UNDERLINE}$message${RESET}"
-            ;;
-        *)
-            echo "$type $message"
-            ;;
-    esac
-}
-
-_verbose_run() {  # Print command before running it
-    _echo --command "$1"
-    eval "$1"
-}
-
-_has_cmd() {  # Check if command exists
-    # Usage:
-    #    _has_cmd 'cmd'  # Check if cmd exists
-    #    _has_cmd -v/--verbose 'cmd'  # Check if cmd exists, and print error message if not exists
-    local verbose=0
-    if [[ "$1" == '-v' || "$1" == '--verbose' ]]; then
-        verbose=1
-        shift
-    fi
-    if command -v "$@" > /dev/null 2>&1; then  # Command exists
-        return 0
-    else  # Command not exists
-        [[ "$verbose" == 1 ]] && _echo --err "Command not found: $1"
-        return 1
-    fi
-}
 
 fzfcd() {  # Use fzf to select a file, and cd to its directory
     _has_cmd --verbose 'fzf' || return 1  # If fzf not installed, return False
