Update zshrc

diff --git a/Zsh/zshrc b/Zsh/zshrc
--- a/Zsh/zshrc
+++ b/Zsh/zshrc
@@ -97,13 +97,12 @@ esac
 export NVM_LAZY_LOAD=true  # Lazy load for zsh-nvm
 
 # Python User Site-Package Binaries
-if command -v python3 > /dev/null 2>&1; then
+if _has_cmd python3; then
     export PATH="$(python3 -m site --user-base)/bin:$PATH"
 fi
 
 # Init Zoxide (z and zi)
-if command -v zoxide > /dev/null 2>&1; then
-    #export _ZO_FZF_OPTS="--preview 'bat --color=always --line-range=:100 {}' --preview-window up"  # Set fzf options for Zoxide
+if _has_cmd zoxide; then
     eval "$(zoxide init zsh)"
 fi
 
@@ -166,22 +165,43 @@ _verbose_run() {  # Print command before running it
     eval "$1"
 }
 
+_has_cmd() {  # Check if command exists
+    # Usage:
+    #    _has_cmd 'cmd'  # Check if cmd exists
+    #    _has_cmd -v/--verbose 'cmd'  # Check if cmd exists, and print error message if not exists
+    local verbose=0
+    if [[ "$1" == '-v' || "$1" == '--verbose' ]]; then
+        verbose=1
+        shift
+    fi
+    if command -v "$@" > /dev/null 2>&1; then  # Command exists
+        return 0
+    else  # Command not exists
+        [[ "$verbose" == 1 ]] && _echo --err "Command not found: $1"
+        return 1
+    fi
+}
+
 fzfcd() {  # Use fzf to select a file, and cd to its directory
+    _has_cmd --verbose 'fzf' || return 1  # If fzf not installed, return False
     cd "$(dirname "$(fzf --preview 'bat --color=always --line-range=:100 {}' --preview-window up)")"
 }
 
 up() {  # Upgrade all packages
     upgrade_pipx() {
         _echo --title 'Upgrade Pipx Packages'
+        _has_cmd --verbose 'pipx' || return 1  # If pipx not installed, return False
         _verbose_run "pipx upgrade-all"  # 20s
     }
     update_pip() {
         _echo --title 'Update pip'
+        _has_cmd --verbose 'python3' || return 1  # If python3 not installed, return False
         _verbose_run "python3 -m pip install --upgrade pip"
     }
     upgrade_brew() {
         if [[ "$(uname -s)" == "Darwin" ]]; then  # Only work on macOS
             _echo --title 'Upgrade Brew Packages'
+            _has_cmd --verbose 'brew' || return 1  # If brew not installed, return False
             _verbose_run 'brew update'
             _verbose_run 'brew upgrade'
             _verbose_run 'brew list --cask | xargs brew upgrade --cask'
@@ -192,6 +212,7 @@ up() {  # Upgrade all packages
     upgrade_apt() {
         if [[ "$(uname -s)" == "Linux" ]]; then  # Only work on Linux
             _echo --title 'Upgrade Apt Packages'
+            _has_cmd --verbose 'apt' || return 1  # If apt not installed, return False
             _verbose_run 'sudo apt update'
             _verbose_run 'sudo apt dist-upgrade -y'
             _verbose_run 'sudo apt auto-remove -y'
@@ -200,11 +221,13 @@ up() {  # Upgrade all packages
     upgrade_snap() {
         if [[ "$(uname -s)" == "Linux" ]]; then  # Only work on Linux
             _echo --title 'Upgrade Snap Packages'
+            _has_cmd --verbose 'snap' || return 1  # If snap not installed, return False
             _verbose_run 'sudo snap refresh'
         fi
     }
     update_omz() {
         _echo --title 'Update Oh-My-Zsh'
+        _has_cmd --verbose 'omz' || return 1  # If omz not installed, return False
         _verbose_run 'omz update'
     }
     local upgrades=('pipx' 'brew' 'apt' 'snap')  # Available package managers for upgrades
@@ -237,6 +260,8 @@ venv() {  # Deactivate if in a venv, or activate .venv/bin/activate
         _verbose_run "deactivate"
         return
     fi
+    # check uv command
+    _has_cmd --verbose 'uv' || return 1
     # If .venv/ not exists, create venv and relaunch the function.
     if [[ ! -d "./.venv" ]]; then
         _verbose_run "uv venv"  # create venv
